# Generated by Django 5.0.3 on 2024-04-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_happymeal_feeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='happymeal',
            field=models.ManyToManyField(to='main_app.happymeal'),
        ),
    ]
