# Generated by Django 5.0.3 on 2024-04-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_burger_happymeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burger',
            old_name='breed',
            new_name='burgertype',
        ),
    ]
